### ISSUE TITLE
stop using moonscript

### ISSUE THREAD

**Issue by LennyPenny** [Nayruden/ulx#1]

**Comment by meepen** [comment]
:+1:

**Comment by meepen** [comment]
Meepen Ƹ̵̡Ӝ̵̨̄Ʒ: no one is going to develop in a language besides glua or c++ for gmod
Lenny. (1): https://github.com/TeamUlysses/ulx4/issues/1
Meepen Ƹ̵̡Ӝ̵̨̄Ʒ: just for one addon

**Comment by Nayruden** [comment]
Thanks for your feedback. As always, if you would like us to consider your suggestions, you need to give reasons and not one liners.
