### ISSUE TITLE
I just wanted to let you know how excited we all are for a revamped ULX!

### ISSUE THREAD

**Issue by anderson2927** [Nayruden/ulx#10]
I just wanted to let you know how excited we all are for a revamped ULX! :)

We love ULX! Garry's Mod is one of a kind in that it's the only game that allows as much community created control as it does. ULX powers the servers of this!

It's very important to everybody so please don't forget about it! We appreciate your work so much!

**Comment by Nayruden** [comment]
Thank you for the kind words, you all are the reason why we do what we do.

We have not forgotten about ULX4, though the team's time has been diverted to other things the past few months with marriages and children.
